// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUnQ0WJpezkPcHRHAuR4n8EQAghjKRzMA',
    appId: '1:362045617351:web:1442787a24915bdacb3ae2',
    messagingSenderId: '362045617351',
    projectId: 'mini-social-app-39179',
    authDomain: 'mini-social-app-39179.firebaseapp.com',
    storageBucket: 'mini-social-app-39179.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaE6Kzswfl_9ZOHDRkHvGH_pjY12qAAyU',
    appId: '1:362045617351:android:873252e7ee61a793cb3ae2',
    messagingSenderId: '362045617351',
    projectId: 'mini-social-app-39179',
    storageBucket: 'mini-social-app-39179.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJXb2P1R9rD42iDRyu6S_XX8XK10AmO80',
    appId: '1:362045617351:ios:d7966eb97ca36058cb3ae2',
    messagingSenderId: '362045617351',
    projectId: 'mini-social-app-39179',
    storageBucket: 'mini-social-app-39179.appspot.com',
    iosBundleId: 'com.example.socialMessager',
  );
}
